version: "3.8"

services:
  app1:
    build: .
    container_name: mockup-api-01
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    networks:
      - backend

  app2:
    build: .
    container_name: mockup-api-02
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    networks:
      - backend

  app3:
    build: .
    container_name: mockup-api-03
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15-alpine
    container_name: mockup-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: mockup-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-8082}:80"
    depends_on:
      - db
    networks:
      - backend

  haproxy:
    image: haproxy:latest
    container_name: mockup-haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /etc/letsencrypt/live/tu_dominio/fullchain.pem:/etc/haproxy/certs/fullchain.pem
      - /etc/letsencrypt/live/tu_dominio/privkey.pem:/etc/haproxy/certs/privkey.pem
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - backend

networks:
  backend:
    driver: bridge
