version: "3.8"

services:
  app1:
    build: .
    container_name: mockup-api-01
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_SESSION_REDIS_NAMESPACE=spring:session
    depends_on:
      - db
      - redis
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app2:
    build: .
    container_name: mockup-api-02
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_SESSION_REDIS_NAMESPACE=spring:session
    depends_on:
      - db
      - redis
    networks:
      - backend

  app3:
    build: .
    container_name: mockup-api-03
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_SESSION_REDIS_NAMESPACE=spring:session
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:15-alpine
    container_name: mockup-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: mockup-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "9090:80"
    depends_on:
      - db
    networks:
      - backend

  haproxy:
    image: haproxy:latest
    container_name: mockup-haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /etc/letsencrypt/live/armandogl.turnos.do:/etc/letsencrypt/live/armandogl.turnos.do
      - /etc/letsencrypt/archive/armandogl.turnos.do:/etc/letsencrypt/archive/armandogl.turnos.do
      - /etc/letsencrypt/renewal/armandogl.turnos.do.conf:/etc/letsencrypt/renewal/armandogl.turnos.do.conf
    user: root
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: mockup-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
